version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  django:
    build:
      context: .
      dockerfile: compose/django/develop/Dockerfile
    volumes:
      - .:/app
    environment:
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    env_file: ./env/dev.env
    command: /start_dev.sh

  postgres:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    ports:
      - "5433:5432"  # Expose port 5433 to use with Postgresql client on host machine
    env_file: ./env/dev.env
