version: '2'

volumes:
  postgres_data: {}

services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - $HOME/postgresql_baks/:/backups
    env_file: ./env/prod.env

  redis:
    image: redis:latest

  django:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: compose/django/production/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file: ./env/prod.env
    command: /gunicorn.sh

  webserver:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    container_name: webserver
    restart: always
    depends_on:
      - django
    volumes:
      - ./staticfiles/:/usr/share/nginx/html/static/:ro
      - ./media/:/usr/share/nginx/html/media/:rw
    environment:
      VIRTUAL_HOST: localhost
      LETSENCRYPT_HOST: localhost
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    depends_on:
      - webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      - ./.nginx/vhost.d:/etc/nginx/vhost.d
      - ./.nginx/html:/usr/share/nginx/html
      - ./.nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      - ./.nginx/vhost.d:/etc/nginx/vhost.d
      - ./.nginx/html:/usr/share/nginx/html
      - ./.nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    depends_on:
      - nginx-gen
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
      - ./.nginx/vhost.d:/etc/nginx/vhost.d
      - ./.nginx/html:/usr/share/nginx/html
      - ./.nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-proxy
